spring:
  application:
    name: dmall-search
  profiles:
    active: dev #默认为开发环境
  security:
    user:
      name: dw
      password: 123456
      roles: SUPERADMIN

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

management:
  endpoint:
    web:
      exposure:
        include: "*" # 公开节点
    #        exclude: env, beans #禁用节点
    shutdown:
      enabled: true
    health:
      show-details: always
      httptrace:
        enabled: true

